### ISSUE TITLE
key mismatch error?

### ISSUE THREAD

**Issue by dodizzle** [srinivasmohan/s3sync#1]
Thanks for writing this btw, been looking for faster way to replicate several huge buckets we have.
I am getting this error reading to source bucket.
# Class:0x57cd2006: The request signature we calculated does not match the signature you provided. Check your key and signing method.

Its the same key and secret that I used for s3cmd which works fine.
I tried to put it on quotes and still fails.
Also I don't have a prefix, just want to sync the whole bucket to I tried commenting the prefix option out but its still failing.

**Comment by srinivasmohan** [comment]
The key mismatch error sounds vaguely familiar... Check if the time/clock on the box you are running is Ok or else ntp sync it.

Not in front of my computer at the moment - detailed reply shortly.

**Comment by srinivasmohan** [comment]
1. If you dont have a prefix, edit the yaml `prefix` param to set it to a space. I tested and this works for me. e.g. `prefix:\b\b` (\b to indicate a space char)
2. Are you sure you don't have any spaces in the `aws_key` and `aws_secret` values? They would be like `aws_secret:\bYOURSECRET\n` (using \b and \n to indicate space and line end)... No spaces anywhere else. If your config is also clean, then I would check the time on your machine to make sure its NTP synced.

I tend to mess up yaml files, so when in doubt, I use a simple ruby->yaml dump to assure myself the config is clean :-)

```
require "yaml"
x={
  "aws_key" => "MYKEY",
  "aws_secret" => "MYSECRET",
  "s3src" => ['bucket1','url1'], 
  "s3dest" => ["bucket2","url2"], 
  "prefix" => " ", #is a space 
  "usemd5" => true
}
puts x.to_yaml

```

**Comment by dodizzle** [comment]
Thanks, it was a prefix problem, once I supplied it with a valid option it worked great.
I owe you a beer.

**Comment by srinivasmohan** [comment]
No problem. Closing issue.
